//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OakGov.Etl.ZumoDestination {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OakGov.Etl.ZumoDestination.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the number of rows per batch. The default is 0 which uses the same size as SSIS internal buffer. .
        /// </summary>
        internal static string BatchSizeDescription {
            get {
                return ResourceManager.GetString("BatchSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnName descriptor in the descriptor file on path {0} is invalid. The schema table does not contain a column with the name {1}..
        /// </summary>
        internal static string ColumnnameDescriptorInvalid {
            get {
                return ResourceManager.GetString("ColumnnameDescriptorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaximumLength descriptor in the descriptor file on path {0} is invalid. The schema table does not contain a column with the name {1}..
        /// </summary>
        internal static string ColunsizeDescriptorInvalid {
            get {
                return ResourceManager.GetString("ColunsizeDescriptorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of seconds before a command times out. A value of 0 indicates infinite time-out. .
        /// </summary>
        internal static string CommandTimeoutDescription {
            get {
                return ResourceManager.GetString("CommandTimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads data into an ADO.NET-compliant database that uses a database table or view. Load data into a new or existing table. For example, use an ADO.NET provider for ODBC to load data into an ODBC destination..
        /// </summary>
        internal static string ComponentDescription {
            get {
                return ResourceManager.GetString("ComponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADO NET Destination.
        /// </summary>
        internal static string ComponentDisplayName {
            get {
                return ResourceManager.GetString("ComponentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADO NET Destination.
        /// </summary>
        internal static string ComponentName {
            get {
                return ResourceManager.GetString("ComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed connection manager.
        /// </summary>
        internal static string ConnectionDescription {
            get {
                return ResourceManager.GetString("ConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No column information is found for table {1} by querying {0}..
        /// </summary>
        internal static string ConnectionReturnedNullSchema {
            get {
                return ResourceManager.GetString("ConnectionReturnedNullSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Microsoft Corporation; Microsoft SQL Server;.
        /// </summary>
        internal static string ContactInfo1 {
            get {
                return ResourceManager.GetString("ContactInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Corporation; All Rights Reserved; http://www.microsoft.com/sql/support;.
        /// </summary>
        internal static string ContactInfo2 {
            get {
                return ResourceManager.GetString("ContactInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType descriptor in the descriptor file on path {0} is invalid. The schema table does not contain a column with the name {1}..
        /// </summary>
        internal static string DatatypeDescriptorInvalid {
            get {
                return ResourceManager.GetString("DatatypeDescriptorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalRequest_post: &apos;{0}&apos;. The external request has completed.&quot;.
        /// </summary>
        internal static string DiagnosticPost {
            get {
                return ResourceManager.GetString("DiagnosticPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalRequest_pre: The object is ready to make the following external request: &apos;{0}&apos;..
        /// </summary>
        internal static string DiagnosticPre {
            get {
                return ResourceManager.GetString("DiagnosticPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADO NET Destination Error Output.
        /// </summary>
        internal static string ErrorOutputName {
            get {
                return ResourceManager.GetString("ErrorOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert the schema table obtained by querying the connection to a standard format..
        /// </summary>
        internal static string FailureConvertTable {
            get {
                return ResourceManager.GetString("FailureConvertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve column properties by executing SELECT statement with schema only option from the database. The problem is {0}. However, this does not mean everything has failed. The next attempt is to try to get schema table by querying connection..
        /// </summary>
        internal static string FailureGetMetadataTableByCommand {
            get {
                return ResourceManager.GetString("FailureGetMetadataTableByCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve column properties by querying the connection. The problem is {0}..
        /// </summary>
        internal static string FailureGetMetadataTableByConnection {
            get {
                return ResourceManager.GetString("FailureGetMetadataTableByConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descriptor files on path {0} does not contain schema information for connection of type {1}. .
        /// </summary>
        internal static string FailureToLoadSchema {
            get {
                return ResourceManager.GetString("FailureToLoadSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADO NET Destination Input.
        /// </summary>
        internal static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My New String.
        /// </summary>
        internal static string NewString {
            get {
                return ResourceManager.GetString("NewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumericScale descriptor in the descriptor file on path {0} is invalid. The schema table does not contain a column with the name {1}..
        /// </summary>
        internal static string NumericaScaleInvalid {
            get {
                return ResourceManager.GetString("NumericaScaleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumericPrecision descriptor in the descriptor file on path {0} is invalid. The schema table does not contain a column with the name {1}..
        /// </summary>
        internal static string NumericPrecisionDescriptorInvalid {
            get {
                return ResourceManager.GetString("NumericPrecisionDescriptorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the number of milliseconds before the component times out..
        /// </summary>
        internal static string ReadTimeoutDescription {
            get {
                return ResourceManager.GetString("ReadTimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider returned an empty schema table..
        /// </summary>
        internal static string SelectReturnEmptyTable {
            get {
                return ResourceManager.GetString("SelectReturnEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table or view.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Destination database table name..
        /// </summary>
        internal static string TableNameDescription {
            get {
                return ResourceManager.GetString("TableNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type and Assembly information: &apos;{0}&apos;..
        /// </summary>
        internal static string TypeAssemblyInfo {
            get {
                return ResourceManager.GetString("TypeAssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize file reader for reading the file: {0}.
        /// </summary>
        internal static string UnableToLoadMappingFile_UnableToCreateFileStreamForOpen {
            get {
                return ResourceManager.GetString("UnableToLoadMappingFile_UnableToCreateFileStreamForOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create XML serializer for type &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string UnableToLoadMappingFile_UnableToCreateSerializer {
            get {
                return ResourceManager.GetString("UnableToLoadMappingFile_UnableToCreateSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize an XML validating file reader: {0}.
        /// </summary>
        internal static string UnableToLoadMappingFile_UnableToCreateValidatingReader {
            get {
                return ResourceManager.GetString("UnableToLoadMappingFile_UnableToCreateValidatingReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load mapping file: {0}.
        /// </summary>
        internal static string UnableToLoadMappingFile_UnableToDeserializeFile {
            get {
                return ResourceManager.GetString("UnableToLoadMappingFile_UnableToDeserializeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read XML schema to verify file correctness: {0}.
        /// </summary>
        internal static string UnableToLoadMappingFile_UnableToReadSchema {
            get {
                return ResourceManager.GetString("UnableToLoadMappingFile_UnableToReadSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load provider specific information because the specified directory &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string UnableToLoadProviderInfos_DirectoryDoesntExist {
            get {
                return ResourceManager.GetString("UnableToLoadProviderInfos_DirectoryDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load provider specific information because the following file is not available: {0}..
        /// </summary>
        internal static string UnableToLoadProviderInfos_FileMissing {
            get {
                return ResourceManager.GetString("UnableToLoadProviderInfos_FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the file with provider descriptors: {0}..
        /// </summary>
        internal static string UnableToLoadProviderInfos_UnableToDeserializeFile {
            get {
                return ResourceManager.GetString("UnableToLoadProviderInfos_UnableToDeserializeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to use the SqlBulkCopy interface to improve the performance of bulk insert operations. Only certain providers support this interface..
        /// </summary>
        internal static string UseBulkInsertDescription {
            get {
                return ResourceManager.GetString("UseBulkInsertDescription", resourceCulture);
            }
        }
    }
}
